sudo: required
services:
  - docker
before_install:
  - docker build -t thouseefkm/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true thouseefkm/react-test npm run test

after_success:
  - docker build -t thouseefkm/multi-client ./client
  - docker build -t thouseefkm/multi-nginx ./nginx
  - docker build -t thouseefkm/multi-server ./server
  - docker build -t thouseefkm/multi-worker ./worker

  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push them to Docker Hub
  - docker push thouseefkm/multi-client
  - docker push thouseefkm/multi-nginx
  - docker push thouseefkm/multi-server
  - docker push thouseefkm/multi-worker


deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-146537443268"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY