language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t thouseefkm/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true thouseefkm/react-test npm run test

after_success:
  - docker build -t thouseefkm/multi-client ./client
  - docker build -t thouseefkm/multi-nginx ./nginx
  - docker build -t thouseefkm/multi-server ./server
  - docker build -t thouseefkm/multi-worker ./worker

  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push them to Docker Hub
  - docker push thouseefkm/multi-client
  - docker push thouseefkm/multi-nginx
  - docker push thouseefkm/multi-server
  - docker push thouseefkm/multi-worker

